[package]
authors = ["Skilfingr <skilvingr@gmail.com>"]
name = "emulator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kaesar-emulator"
path = "src/main.rs"

[dependencies]
kaesar-core = { path = "../core", default-features = false, features = ["sim"] }
kaesar = { path = "../kaesar", default-features = false, features = ["sim"] }
sdl2 = "0.38.0"
